application: chromatic-tree-459
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /views
  static_dir: views

- url: /scripts
  static_dir: scripts

- url: /
  static_files: views/view1.html
  upload: views/view1.html

- url: /.*
  script: server.application

  
libraries:
- name: webapp2
  version: latest

