application: chromatic-tree-459
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: helloworld.application

  
libraries:
- name: webapp2
  version: latest

