application: s~chromatic-tree-459
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/templates
  static_dir: templates 

- url: /static/stylesheets
  static_dir: stylesheets

- url: /static/views
  static_dir: views

- url: /static/scripts
  static_dir: scripts

- url: /static/controllers
  static_dir: controllers
  
- url: /
  login: required
  static_files: views/index.html
  upload: views/index.html

- url: /.*
  login: required
  script: server.application

  
libraries:
- name: webapp2
  version: latest

builtins:
- remote_api: on

auto_id_policy: legacy

