application: s~chromatic-tree-459
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /templates
  static_dir: templates 

- url: /stylesheets
  static_dir: stylesheets

- url: /views
  static_dir: views

- url: /scripts
  static_dir: scripts

- url: /
  login: required
  static_files: views/index.html
  upload: views/index.html

- url: /.*
  login: required
  script: server.application

  
libraries:
- name: webapp2
  version: latest

builtins:
- remote_api: on

auto_id_policy: legacy

