application: chromatic-tree-459
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /
  static_files: view1.html
  upload: view1.html

- url: /(.*\.(html|css|js))$
  static_files: ./\1
  upload: ./(.*\.(html|css|js))$

- url: /.*
  script: server.application

  
libraries:
- name: webapp2
  version: latest

